version: "3.8"

services:
  lab-nginx:
    container_name: kdm-lab-nginx
    depends_on:
      - kdm-lab
      - kdm-lab-api
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80
  kdm-lab:
    container_name: kdm-lab
    image: jasoniv/kdm-lab:latest
  kdm-lab-api:
    container_name: kdm-lab-api
    image: jasoniv/kdm-lab-api:latest
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8001 --reload"
    ports: 
      - 8001:8001
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@kdm-lab-db/KDMLAB
      - SECRET_KEY=secret
      - ALGORITHM=HS256
    depends_on:
      - kdm-lab-db
  kdm-lab-db:
    container_name: kdm-lab-db
    image: postgres:13-alpine
    volumes:
      - kdm-lab-data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=KDMLAB
volumes:
  kdm-lab-data:
